image: 'node:12.13.1-buster'

# before_script:
  # - npm install

cache:
  paths:
    - node_modules/

# test:
#   stage: test
#   before_script:
#     - npm install
#   script:
#     - node --version

# ssh:
#   stage: deploy
#   script:
#     - ssh root@$SERVER_IP

install_env:
  stage: deploy
  before_script:
    - apt-get update
    - 'which ssh-agent || apt-get install openssh-client -y'
    - 'which git || apt-get install -y git '
    - 'which rsync || apt-get install -y rsync '
    - npm i -g pm2

    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    # Install pm2
    - ssh $SERVER_USER@$SERVER_IP "npm install -g pm2"
    # Make folder
    - ssh $SERVER_USER@$SERVER_IP "[ ! -e /root/$APP_NAME ] || rm -r /root/$APP_NAME; mkdir -p /root/$APP_NAME"
    # Copy file
    - rsync -zr ./* $SERVER_USER@$SERVER_IP:/root/$APP_NAME
    # # Start app
    - ssh $SERVER_USER@$SERVER_IP 'cd /root/$APP_NAME && npm install ;echo $APP_NAME; pm2 start index.js --name $APP_NAME -- --port $APP_PORT'
